version: '3.4'

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    hostname: mssql
    environment:
      MSSQL_SA_PASSWORD: "<VeryStrongPassw0rd>"
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    ports:
      - "1433:1433"
